export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const TURBING_PRESSURE_DATA = "TURBING_PRESSURE_DATA";
export const FLARETEMP_DATA = "FLARETEMP_DATA";
export const INJVALVEOPEN_DATA = "INJVALVEOPEN_DATA";
export const OILTEMP_DATA = "OILTEMP_DATA";
export const CASINGPRESSURE_DATA = "CASINGPRESSURE_DATA";
export const WATERTEMP_DATA = "WATERTEMP_DATA";
